// SPDX-License-Identifier: AGPL-3.0-or-later
// The trusted half of media execution. The parser receives only local HTTP
// handles; URLs, credentials, DNS and outbound connections stay in this process.
package main

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"
)

type source struct {
	URL     string
	Headers http.Header
}

type broker struct {
	sources []source
	client  *http.Client
}

var byteRange = regexp.MustCompile(`^bytes=[0-9]+-[0-9]*$`)

func newBroker() *broker {
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.Proxy = nil
	transport.DisableCompression = true
	transport.ResponseHeaderTimeout = 30 * time.Second
	return &broker{client: &http.Client{Transport: transport,
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error { return http.ErrUseLastResponse }}}
}

func (b *broker) add(raw string, headers http.Header) (string, error) {
	u, err := url.Parse(raw)
	if err != nil || (u.Scheme != "https" && u.Scheme != "http") || u.Hostname() == "" || u.User != nil || u.Fragment != "" {
		return "", errors.New("invalid media source URL")
	}
	if len(b.sources) >= 128 {
		return "", errors.New("too many media inputs")
	}
	b.sources = append(b.sources, source{raw, headers.Clone()})
	return "http://127.0.0.1/" + strconv.Itoa(len(b.sources)-1), nil
}

func (b *broker) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// Never act as a forward proxy: authority, path, method and Range are the
	// entire parser-visible contract. No supplied headers reach object storage.
	index, err := strconv.Atoi(strings.TrimPrefix(r.URL.Path, "/"))
	if err != nil || index < 0 || index >= len(b.sources) || r.URL.Path != "/"+strconv.Itoa(index) ||
		r.URL.RawQuery != "" || r.URL.IsAbs() || r.Host != "127.0.0.1" ||
		(r.Method != http.MethodGet && r.Method != http.MethodHead) || r.ContentLength != 0 || len(r.TransferEncoding) != 0 {
		http.Error(w, "media request denied", http.StatusForbidden)
		return
	}
	span := r.Header.Get("Range")
	if len(span) > 96 || (span != "" && !byteRange.MatchString(span)) {
		http.Error(w, "media range denied", http.StatusForbidden)
		return
	}
	s := b.sources[index]
	request, err := http.NewRequestWithContext(r.Context(), r.Method, s.URL, nil)
	if err != nil {
		http.Error(w, "media input unavailable", 502)
		return
	}
	request.Header = s.Headers.Clone()
	if span != "" {
		request.Header.Set("Range", span)
	}
	response, err := b.client.Do(request)
	if err != nil {
		http.Error(w, "media input unavailable", 502)
		return
	}
	defer response.Body.Close()
	if response.StatusCode != 200 && response.StatusCode != 206 && response.StatusCode != 416 {
		// In particular, do not forward redirects, cookies, error bodies or signed URLs.
		http.Error(w, "media input unavailable", 502)
		return
	}
	for _, key := range []string{"Content-Length", "Content-Range", "Content-Type", "Accept-Ranges"} {
		if value := response.Header.Get(key); value != "" {
			w.Header().Set(key, value)
		}
	}
	w.WriteHeader(response.StatusCode)
	if r.Method != http.MethodHead {
		_, _ = io.Copy(w, response.Body)
	}
}

func parseHeaders(raw string) (http.Header, error) {
	h := make(http.Header)
	for _, line := range strings.Split(strings.TrimSuffix(raw, "\r\n"), "\r\n") {
		if line == "" {
			continue
		}
		key, value, ok := strings.Cut(line, ":")
		key = http.CanonicalHeaderKey(key)
		if !ok || strings.ContainsAny(value, "\r\n") || (key != "Referer" && key != "Authorization" && key != "User-Agent") {
			return nil, errors.New("unsupported media input header")
		}
		h.Add(key, strings.TrimSpace(value))
	}
	return h, nil
}

func remote(value string) bool {
	return strings.HasPrefix(value, "https://") || strings.HasPrefix(value, "http://")
}

// These manifests are generated by trusted callers, never inferred from media.
// Unknown directives fail closed rather than exposing their URLs to the parser.
func (b *broker) manifest(body []byte, headers http.Header) ([]byte, error) {
	var output bytes.Buffer
	scanner := bufio.NewScanner(bytes.NewReader(body))
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || line == "ffconcat version 1.0" {
			fmt.Fprintln(&output, line)
			continue
		}
		if !strings.HasPrefix(line, "file '") || !strings.HasSuffix(line, "'") {
			return nil, errors.New("unsupported media concat directive")
		}
		path := strings.TrimSuffix(strings.TrimPrefix(line, "file '"), "'")
		parts := strings.Split(path, "'\\''")
		for _, part := range parts {
			if strings.ContainsAny(part, "'\\\r\n\x00") {
				return nil, errors.New("unsupported media concat path")
			}
		}
		path = strings.Join(parts, "'")
		if remote(path) {
			var err error
			path, err = b.add(path, headers)
			if err != nil {
				return nil, err
			}
		} else if !filepath.IsAbs(path) {
			return nil, errors.New("media concat path must be absolute")
		}
		fmt.Fprintf(&output, "file '%s'\n", strings.ReplaceAll(path, "'", "'\\''"))
	}
	return output.Bytes(), scanner.Err()
}

func (b *broker) prepare(args []string, stdin io.Reader, work string) ([]string, io.Reader, error) {
	var result []string
	headers := make(http.Header)
	concat := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "-headers" {
			if i+1 >= len(args) {
				return nil, nil, errors.New("missing media headers")
			}
			i++
			h, err := parseHeaders(args[i])
			if err != nil {
				return nil, nil, err
			}
			for key, values := range h {
				headers[key] = values
			}
			continue
		}
		if arg == "-f" && i+1 < len(args) {
			concat = args[i+1] == "concat"
		}
		if arg == "-i" && concat {
			if i+1 >= len(args) {
				return nil, nil, errors.New("missing concat input")
			}
			i++
			input := args[i]
			var body []byte
			var err error
			if input == "pipe:0" || input == "-" {
				body, err = io.ReadAll(io.LimitReader(stdin, 1024*1024+1))
			} else {
				var file *os.File
				file, err = os.Open(input)
				if err == nil {
					body, err = io.ReadAll(io.LimitReader(file, 1024*1024+1))
					file.Close()
				}
			}
			if err != nil || len(body) > 1024*1024 {
				return nil, nil, errors.New("cannot read media concat manifest")
			}
			body, err = b.manifest(body, headers)
			if err != nil {
				return nil, nil, err
			}
			path := filepath.Join(work, "concat-"+strconv.Itoa(i))
			if err = os.WriteFile(path, body, 0600); err != nil {
				return nil, nil, err
			}
			result = append(result, "-i", path)
			if input == "pipe:0" || input == "-" {
				stdin = bytes.NewReader(nil)
			}
			headers = make(http.Header)
			concat = false
			continue
		}
		if remote(arg) {
			var err error
			arg, err = b.add(arg, headers)
			if err != nil {
				return nil, nil, err
			}
			headers = make(http.Header)
		}
		result = append(result, arg)
	}
	return result, stdin, nil
}

func socketPair(kind int) (*os.File, *os.File, error) {
	fds, err := syscall.Socketpair(syscall.AF_UNIX, kind|syscall.SOCK_CLOEXEC, 0)
	if err != nil {
		return nil, nil, err
	}
	return os.NewFile(uintptr(fds[0]), "broker"), os.NewFile(uintptr(fds[1]), "parser"), nil
}

type connections struct {
	queue chan net.Conn
	done  chan struct{}
	once  sync.Once
}

func (l *connections) Accept() (net.Conn, error) {
	select {
	case connection := <-l.queue:
		return connection, nil
	case <-l.done:
		return nil, net.ErrClosed
	}
}
func (l *connections) Close() error   { l.once.Do(func() { close(l.done) }); return nil }
func (l *connections) Addr() net.Addr { return &net.UnixAddr{Name: "media-broker", Net: "unix"} }

func serve(ctx context.Context, control *net.UnixConn, b *broker) {
	defer control.Close()
	listener := &connections{queue: make(chan net.Conn), done: make(chan struct{})}
	server := &http.Server{Handler: b, ReadHeaderTimeout: 10 * time.Second, IdleTimeout: 30 * time.Second,
		MaxHeaderBytes: 8192, BaseContext: func(net.Listener) context.Context { return ctx }}
	go func() { <-ctx.Done(); control.Close(); server.Close(); listener.Close() }()
	go server.Serve(listener)
	// Limit parser-created connections over the entire invocation to bound abuse.
	for count := 0; count < 4096; count++ {
		var request [2]byte
		n, err := control.Read(request[:])
		if err != nil || n != 1 || request[0] != 'C' {
			return
		}
		parent, child, err := socketPair(syscall.SOCK_STREAM)
		if err != nil {
			return
		}
		connection, err := net.FileConn(parent)
		parent.Close()
		if err != nil {
			child.Close()
			return
		}
		_, _, err = control.WriteMsgUnix([]byte{'C'}, syscall.UnixRights(int(child.Fd())), nil)
		child.Close()
		if err != nil {
			connection.Close()
			return
		}
		select {
		case listener.queue <- connection:
		case <-ctx.Done():
			connection.Close()
			return
		}
	}
}

func run() int {
	args := os.Args[1:]
	separator := -1
	for i, arg := range args {
		if arg == "--" {
			separator = i
			break
		}
	}
	if separator < 0 || separator+1 >= len(args) {
		fmt.Fprintln(os.Stderr, "media broker: missing executable")
		return 126
	}
	tmp, err := os.MkdirTemp("", "mave-broker-")
	if err != nil {
		return 126
	}
	defer os.RemoveAll(tmp)
	work := filepath.Join(tmp, "work")
	root := filepath.Join(tmp, "root")
	if os.Mkdir(work, 0700) != nil || os.Mkdir(root, 0700) != nil {
		return 126
	}
	b := newBroker()
	prepared, input, err := b.prepare(args[separator+2:], os.Stdin, work)
	if err != nil {
		fmt.Fprintln(os.Stderr, "media broker: invalid input configuration")
		return 126
	}
	parent, child, err := socketPair(syscall.SOCK_SEQPACKET)
	if err != nil {
		return 126
	}
	connection, err := net.FileConn(parent)
	parent.Close()
	if err != nil {
		child.Close()
		return 126
	}
	defer connection.Close()
	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
	defer cancel()
	go serve(ctx, connection.(*net.UnixConn), b)
	launcherArgs := append([]string{"--broker", "--root", root, "--scratch", work}, args[:separator]...)
	launcherArgs = append(launcherArgs, "--", args[separator+1])
	launcherArgs = append(launcherArgs, prepared...)
	command := exec.CommandContext(ctx, "mave-media-sandbox", launcherArgs...)
	command.Stdin = input
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	command.ExtraFiles = []*os.File{child}
	err = command.Start()
	child.Close()
	if err == nil {
		err = command.Wait()
	}
	if err == nil {
		return 0
	}
	var exit *exec.ExitError
	if errors.As(err, &exit) && exit.ExitCode() >= 0 {
		return exit.ExitCode()
	}
	fmt.Fprintln(os.Stderr, "media broker: confined command failed")
	return 126
}

func main() { os.Exit(run()) }
