import Config

# Configure your database
config :mave_core, MaveCore.Repo,
  username: System.get_env("POSTGRES_USER", "postgres"),
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: System.get_env("POSTGRES_HOST") || "localhost",
  port: String.to_integer(System.get_env("POSTGRES_PORT") || "5432"),
  database: "mave_core_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :mave_core, :s3,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID") || "minioadmin",
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY") || "minioadmin",
  endpoint: System.get_env("S3_ENDPOINT") || "http://localhost:9000",
  region: System.get_env("AWS_REGION") || "us-east-1"

config :mave_core, MaveCore.ClickHouseRepo,
  # In dev docker-compose, hostname is localhost for the host machine,
  # or 'clickhouse' if running inside docker (but mix runs on host usually or inside 'app').
  # Assuming 'mix phx.server' runs on host:
  hostname: System.get_env("CLICKHOUSE_HOST") || "localhost",
  port: 8123,
  database: System.get_env("CLICKHOUSE_DATABASE", "mave_metrics"),
  username: System.get_env("CLICKHOUSE_USER", "default"),
  password: System.get_env("CLICKHOUSE_PASSWORD", "password"),
  scheme: "http",
  settings: [async_insert: 0, wait_for_async_insert: 1],
  priv: "priv/clickhouse_repo"

config :mave_core, :metrics_ingestion, clickhouse_batch_timeout: 100

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mave_core, MaveCoreWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "m7NQl01Q9Lmr11JjowpF/zfLc5xYQedPWEajVBp9FBwbOq/8KlCqu72Ng83WN8jm",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:mave_core, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:mave_core, ~w(--watch)]},
    storybook_tailwind: {Tailwind, :install_and_run, [:storybook, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :mave_core, MaveCoreWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/mave_core_web/router\.ex$"E,
      ~r"lib/mave_core_web/(controllers|live|components)/.*\.(ex|heex)$"E,
      # Storybook stories
      ~r"storybook/.*(exs)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :mave_core, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
